const projects=[
{title:'MindVault',type:'backend',meta:'INTERNSHIP / INTELLIGENT DOCUMENT PROCESSING',desc:'A backend that turns documents into usable knowledge. Built during my internship at Zasya Online Solutions.',tech:['Python','FastAPI','MongoDB Atlas','AWS S3'],visual:'code',label:'Backend engineering',details:['Engineered REST APIs and modular backend services for an intelligent document management platform.','Developed asynchronous document ingestion supporting PDF, DOCX, XLSX, PPTX, CSV, TXT, images, and audio.','Implemented parsing, OCR, speech-to-text integration, text preprocessing, and chunk generation.','Integrated AWS S3, MongoDB Atlas, and Razorpay; validated services with Pytest and Swagger UI.'],note:'Internship contribution · May–June 2026. This describes my backend work on the platform.'},
{title:'Spotify Tools',type:'data',meta:'PERSONAL PROJECT / CS50 PYTHON',desc:'A desktop companion for accessing playlists and shuffle controls through the Spotify Web API.',tech:['Python','Spotipy','Tkinter'],visual:'Spotify Tools',sub:'PLAYLISTS / SHUFFLE / PYTHON',details:['Created a Tkinter desktop interface for a CS50 Python final project.','Connected to the Spotify Web API using Spotipy.','Implemented login, playlist viewing, shuffle, and logout.'],note:'A Python desktop application focused on API integration and a practical user interface.'},
{title:'Face & Eye Detection',type:'ai',meta:'COMPUTER VISION / AUG 2024',desc:'Real-time face and eye detection with OpenCV and Haar cascades.',tech:['Python','OpenCV','Haar cascades'],visual:'Face → Features',sub:'CAPTURE / DETECT / DISPLAY',details:['Built a real-time face and eye detection system using OpenCV.','Used Haar cascade classifiers to identify facial regions.','Worked on detection pipeline performance for consumer hardware.'],note:'Academic project · GITAM, Hyderabad.'},
{title:'Neural Network Model',type:'ai',meta:'MACHINE LEARNING / SEP 2024',desc:'Exploring how neural networks learn through backpropagation and gradient descent.',tech:['Python','TensorFlow','Keras'],visual:'Input → Learn',sub:'FORWARD / LOSS / BACKPROPAGATION',details:['Developed a foundational neural network using TensorFlow and Keras.','Demonstrated backpropagation and gradient descent.','Implemented supervised classification on structured datasets.'],note:'Academic project focused on machine learning fundamentals.'},
{title:'Student Job Status Analysis',type:'data',meta:'DATA ENGINEERING / FEB 2024',desc:'From placement records to queryable data, using Python, Pandas, and SQLite.',tech:['Python','Pandas','SQLite3'],visual:'CSV → SQL',sub:'INGEST / FILTER / ANALYZE',details:['Built a system to ingest placement CSV records into an SQLite database.','Used Python and Pandas to process structured records.','Implemented dynamic SQL queries to filter candidate data using runtime parameters.'],note:'Academic project · GITAM, Hyderabad.'},
{title:'AyuSparsha',type:'backend',meta:'WEB PROJECT / E-COMMERCE PROTOTYPE',desc:'A premium Ayurvedic storefront exploration, with product discovery, categories, and shopping flows.',tech:['E-commerce','UI/UX','Web development'],visual:'AyuSparsha',sub:'TRADITION / EVERYDAY WELLNESS',details:['Developed an Ayurvedic e-commerce website prototype with a botanical visual direction.','Explored product browsing, category navigation, cart, and checkout experiences.','Worked through interactive storefront refinements and payment gateway planning.'],note:'Prototype. Live payment processing and production readiness are not claimed.'},
{title:'Language & Search Foundations',type:'data',meta:'COURSEWORK / ALGORITHMS',desc:'Hands-on explorations of parsing, numeric recognition, and graph search.',tech:['C','Automata','Search algorithms'],visual:'Parse. Search.',sub:'TOKENS / STATES / PATHS',details:['Worked on numeric recognition using transition diagrams and C.','Explored recursive descent parsing.','Studied BFS, uniform-cost search, greedy search, and A* through an Indian-city pathfinding assignment.'],note:'Coursework and learning exercises.'}
];
const grid=document.querySelector('#projects');
function render(filter='all'){grid.innerHTML=projects.map((p,i)=>({p,i})).filter(({p})=>filter==='all'||p.type===filter).map(({p,i})=>`<article class="project"><div class="project-visual visual-${i+1}" aria-hidden="true">${p.visual==='code'?'<div class="visual-code"><div class="bar">MINDVAULT / INGESTION PIPELINE</div><div class="code-line"><b>POST</b> /documents/ingest</div><div class="code-line">↓ parse & extract</div><div class="code-line">↓ preprocess & chunk</div><div class="code-line">↓ store & retrieve</div><div class="code-line"><b>200</b> · ready for knowledge</div></div>':`<div class="visual-word">${p.visual}<small>${p.sub}</small></div>`}</div><div class="project-info"><div class="meta">${p.meta}</div><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><button class="project-open" data-project="${i}" style="margin-top:26px" aria-label="Read about ${p.title}">Explore project <span>↗</span></button></div></article>`).join('');}
render();document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)}));
const dialog=document.querySelector('#project-dialog');let opener;grid.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(!b)return;opener=b;const p=projects[Number(b.dataset.project)];document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${p.meta}</p><h2 id="dialog-title">${p.title}</h2><p>${p.desc}</p><h3>What I worked on</h3><ul>${p.details.map(d=>`<li>${d}</li>`).join('')}</ul><div class="tags">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><p style="font-size:13px;margin:24px 0 0">${p.note}</p>`;dialog.showModal()});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>opener?.focus());
const skillData={backend:['Python','FastAPI / Flask','REST APIs','SQL / MySQL','MongoDB Atlas','AWS S3'],ai:['LangChain / Ollama','RAG pipelines','TensorFlow / Keras','OpenCV','Pandas','OCR / speech-to-text'],tools:['Git / GitLab','Pytest','Postman','VS Code','JavaScript','C / C++']};function renderSkills(key){document.querySelector('#skills').innerHTML=skillData[key].map(s=>`<span>${s}</span>`).join('')}renderSkills('backend');document.querySelectorAll('[data-skill]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-skill]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderSkills(b.dataset.skill)}));document.querySelector('#year').textContent=new Date().getFullYear();document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('laxmanprasad.mudigonda@gmail.com');const t=document.querySelector('#toast');t.textContent='Email copied';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}catch{document.querySelector('#copy').textContent='Select the email above to copy'}});
